name: Tests
on:
  pull_request:
    paths-ignore:
      - 'README.md'
  push:
    paths-ignore:
      - 'README.md'
permissions:
  contents: read
env:
  GO_VERSION: '1.18'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: go mod download
      - run: go build -v .
      - run: go vet ./...
      #Does not work with go 1.18 yet
      #- run: go run github.com/golangci/golangci-lint/cmd/golangci-lint run ./internal/arplookup
      - run: go run honnef.co/go/tools/cmd/staticcheck ./internal/arplookup

  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - run: go generate ./...
      - name: git diff
        run: |
          git diff --compact-summary --exit-code || \
            (echo; echo "Unexpected difference in directories after code generation. Run 'go generate ./...' command and commit."; exit 1)
  test:
    name: Terraform Provider Acceptance Tests
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        terraform:
          - '1.0.*'
          - '1.1.*'
          - '1.2.*'
    steps:
      - name: Ensure apt cache is updated
        run: sudo apt update

      - uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Checkout source
        uses: actions/checkout@v3
      - name: Download go modules
        run: go mod download

      - name: Install iproute2
        run: sudo apt-get install -y iproute2
      - name: Get slirp4netns
        run: curl -o tools/slirp4netns --fail -L https://github.com/rootless-containers/slirp4netns/releases/download/v1.2.0/slirp4netns-$(uname -m) && chmod +x tools/slirp4netns
      - name: Run acceptance tests
        env:
          TF_ACC: "1"
        run: tools/pretest.sh
        timeout-minutes: 10
